springdoc:
  swagger-ui:
    oauth:
      client-id: gateway-service
      client-secret: oAVs2jDPpuDrm81QzNWfk7tIoCoF7w9F
      use-pkce-with-authorization-code-grant: true
      authorization-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
      scopes:
        read: Read access
        write: Write access
        update: Update access
        delete: Delete access

spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://myuser:mypassword@localhost:27017/eventstore?authSource=eventstore&replicaSet=rs0
  application:
    name: customer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
server:
  port: 8082
logging:
  level:
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO