spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration

  session:
    store-type: redis
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-route
              uri: ${CUSTOMER_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/customers/**
              filters:
                - AddRequestHeader=X-Tenant,acme
                - AddResponseHeader=X-Customer,customer
                - TokenRelay

  application:
    name: gateway-service
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        security.oauth2: DEBUG
        core.env: DEBUG