springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: 9GWog3K2tTWJA3kFf3uEZIH6anM63iuY
      use-pkce-with-authorization-code-grant: true
      authorization-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
      scopes:
        write: Write access
        update: Update access
        delete: Delete access

spring:
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://myuser:mypassword@localhost:27017/eventstore?authSource=eventstore&replicaSet=rs0
  application:
    name: account-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
server:
  port: 8083
logging:
  level:
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO
